### ISSUE TITLE
Loading 1.9.4 world lockup ,Forge 12.17.0.1976, CraftingCraft 4.0.1 other mods

### ISSUE THREAD

**Issue by iTraumatik** [blay09/CraftCraft#22]
Forge 12.17.0.1976 , CraftingCraft 4.0.1 ,  Java 8 v91 (since its the newest stable secure version of 8)
. I could go back to an earlier version of java but they arent as secure and not recommended versions from Oracle.     When i remove craftingcraft i can load and run my game for hours.  This error looks like something that Forge had problems with Java 8 but was patched for back in 1.7.10.  I dont have full error logs since it locks up and shows 0% on screen.

The logs say
[13:55:34] [Server thread/ERROR]: The following problems were captured during this phase
[13:55:34] [Server thread/WARN]: =============================================================
[13:55:34] [Server thread/WARN]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[13:55:34] [Server thread/WARN]: Offender: org/multimc/EntryPoint.main([Ljava/lang/String;)V
[13:55:34] [Server thread/WARN]: Use FMLCommonHandler.exitJava instead
[13:55:34] [Server thread/WARN]: =============================================================
[13:55:34] [Server thread/ERROR]: Caught exception from Forge
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(Unknown Source) ~[?:1.8.0_91]
    at java.util.TimSort.mergeAt(Unknown Source) ~[?:1.8.0_91]
    at java.util.TimSort.mergeCollapse(Unknown Source) ~[?:1.8.0_91]
    at java.util.TimSort.sort(Unknown Source) ~[?:1.8.0_91]
    at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_91]
    at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_91]
    at java.util.Collections.sort(Unknown Source) ~[?:1.8.0_91]
    at net.minecraftforge.oredict.RecipeSorter.sortCraftManager(RecipeSorter.java:154) ~[forge-1.9.4-12.17.0.1976-universal.jar:?]
    at net.minecraftforge.common.ForgeModContainer.onAvailable(ForgeModContainer.java:409) ~[forge-1.9.4-12.17.0.1976-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:775) ~[Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316) ~[FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518) ~[bcd.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) ~[bcd.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) ~[OneSixLauncher.class:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) ~[OneSixLauncher.class:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) ~[EntryPoint.class:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) ~[EntryPoint.class:?]
[13:55:34] [Server thread/ERROR]: A fatal exception occurred during the server about to start event
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(Unknown Source) ~[?:1.8.0_91]
    at java.util.TimSort.mergeAt(Unknown Source) ~[?:1.8.0_91]
    at java.util.TimSort.mergeCollapse(Unknown Source) ~[?:1.8.0_91]
    at java.util.TimSort.sort(Unknown Source) ~[?:1.8.0_91]
    at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_91]
    at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_91]
    at java.util.Collections.sort(Unknown Source) ~[?:1.8.0_91]
    at net.minecraftforge.oredict.RecipeSorter.sortCraftManager(RecipeSorter.java:154) ~[forge-1.9.4-12.17.0.1976-universal.jar:?]
    at net.minecraftforge.common.ForgeModContainer.onAvailable(ForgeModContainer.java:409) ~[forge-1.9.4-12.17.0.1976-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:775) ~[Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316) ~[FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518) ~[bcd.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) ~[bcd.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) ~[OneSixLauncher.class:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) ~[OneSixLauncher.class:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) ~[EntryPoint.class:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) ~[EntryPoint.class:?]

**Comment by BlayTheNinth** [comment]
The logs are not related to CraftingCraft, CraftingCraft only uses default recipes.

**Comment by iTraumatik** [comment]
Ok, but why when CC is installed it locks up and gives that message, but when i take it out , then i can play minecraft for hours on end without problem.
I put the error here so you can see what is thrown when CC is installed.

OK for science, i made 194 instance with just forge and CC.  Works fine.  Must be a clash with another mod but dont know how to find out.  Not going to add 100+ mods one by one to test further. Ill close this and just not use in my 194 pack.
